apiVersion: v1
kind: Service
metadata:
  name: thanos-store-k8s
  namespace: monitoring
  labels:
    app: thanos-store-k8s
spec:
  clusterIP: None
  selector:
    app: thanos-store-k8s
  ports:
  - name: grpc
    port: 10901
    targetPort: grpc
  - name: http
    port: 9090
    targetPort: http
