apiVersion: v1
kind: Service
metadata:
  name: thanos-query-k8s
  namespace: monitoring
  labels:
    app: thanos-query
    thanos-query: k8s
spec:
  selector:
    app: thanos-query
    thanos-query: k8s
  ports:
  - name: grpc
    port: 10901
    targetPort: grpc
  - name: http
    port: 9090
    targetPort: http
