apiVersion: v1
kind: Service
metadata:
  name: thanos-compact-k8s
  namespace: monitoring
  labels:
    app: thanos-compact-k8s
spec:
  ports:
  - name: http
    port: 10902
    targetPort: http
  selector:
    app: thanos-compact-k8s
